export default [
  {
    component: 'CNavItem',
    name: 'Inicio',
    to: '/dashboard',
    icon: 'cil-home',
  },
  {
    component: 'CNavItem',
    name: 'Análisis',
    to: '/analytics',
    icon: 'cil-chart-pie',
  },
  {
    component: 'CNavItem',
    name: 'Próximos',
    to: '/next',
    icon: 'cil-arrow-right',
  },
  {
    component: 'CNavItem',
    name: 'Disponibilidad',
    to: '/availability',
    icon: 'cil-check-circle',
  },
  {
    component: 'CNavTitle',
    name: 'Negocio',
  },
  {
    component: 'CNavItem',
    name: 'Organizaciones',
    to: '/business/organizations',
    icon: 'cil-briefcase',
  },
  {
    component: 'CNavItem',
    name: 'Cabañas',
    to: '/business/venues',
    icon: 'cil-location-pin',
  },
  {
    component: 'CNavItem',
    name: 'Contactos',
    to: '/business/contacts',
    icon: 'cil-user',
  },
  {
    component: 'CNavItem',
    name: 'Hospedajes',
    to: '/business/accommodations',
    icon: 'cil-calendar',
  },
  {
    component: 'CNavItem',
    name: 'Pagos',
    to: '/business/payments',
    icon: 'cil-dollar',
  },
  {
    component: 'CNavItem',
    name: 'Depósitos',
    to: '/business/deposits',
    icon: 'cil-wallet',
  },
  {
    component: 'CNavItem',
    name: 'Egresos',
    to: '/business/expenses',
    icon: 'cil-cart',
  },
  {
    component: 'CNavTitle',
    name: 'Sistema',
  },
  {
    component: 'CNavItem',
    name: 'Usuarios',
    to: '/users',
    icon: 'cil-people',
  },
  {
    component: 'CNavItem',
    name: 'Perfiles',
    to: '/admin/profiles',
    icon: 'cil-shield-alt',
  },
  {
    component: 'CNavItem',
    name: 'Amenidades',
    to: '/admin/amenities',
    icon: 'cil-list-rich',
  },
  {
    component: 'CNavItem',
    name: 'Categorías de Gastos',
    to: '/admin/expense-categories',
    icon: 'cil-applications',
  },
  {
    component: 'CNavItem',
    name: 'Templates de Mensajes',
    to: '/admin/message-templates',
    icon: 'cil-speech',
  },
  {
    component: 'CNavItem',
    name: 'Proveedores IA',
    to: '/admin/llm-providers',
    icon: 'cil-bolt',
  },
  {
    component: 'CNavItem',
    name: 'Configuración',
    to: '/settings',
    icon: 'cil-settings',
  },
]
